apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "0.4"
        memory: "128Mi"
      requests:
        cpu: "0.2"
        memory: "54Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
